#!/usr/bin/env python

#
# @ACCESS_TOKEN, generated by creating an app, and access token:
#
#     https://developers.facebook.com/apps
#     https://developers.facebook.com/tools/explorer/
#
ACCESS_TOKEN='REPLACE'